receivers:
  hostmetrics:
    scrapers:
      cpu:
      disk:
      filesystem:
      load:
      memory:
      network:
      process:
      processes:
      paging:

  prometheus:
    config:
      scrape_configs:
        - job_name: otel-collector
          scrape_interval: 5s
          static_configs:
            - targets: ['localhost:8888']

  otlp:
    protocols:
      http:
        endpoint: "localhost:4318"

exporters:
  prometheusremotewrite:
    endpoint: 'http://prometheus:9090/api/v1/write'
    tls:
      insecure: true

  zipkin:
    endpoint: http://zipkin:9411/api/v2/spans

  loki:
    endpoint: http://localhost:3100/loki/api/v1/push
    tls:
      insecure: true

processors:
  attributes:
    actions:
      - action: insert
        key: loki.format
        value: raw

  resource:
    attributes:
      - action: insert
        key: loki.resource.labels
        value: app
      - action: insert
        key: app
        value: app-spring

service:
  pipelines:
    metrics:
      receivers: [otlp, hostmetrics, prometheus]
      exporters: [prometheusremotewrite]
    traces:
      receivers: [otlp]
      exporters: [zipkin]
    logs:
      receivers: [otlp]
      processors: [attributes, resource]
      exporters: [loki]
